# Generated by Django 5.0.3 on 2024-04-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='proyectos',
        ),
    ]
