# Generated by Django 5.0.3 on 2024-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50, verbose_name='Periodo')),
                ('job_title', models.CharField(max_length=150, verbose_name='Colgio/Univ.')),
                ('location', models.CharField(max_length=150, verbose_name='Título Obtenido')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiecias',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.CharField(default=0, max_length=150, verbose_name='establecimiento'),
            preserve_default=False,
        ),
    ]
