# Generated by Django 5.0.3 on 2024-04-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_experience_course_period_course_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree_title',
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=150, verbose_name='Cargo ocupado'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Lugar Trabajo'),
        ),
    ]
