# Generated by Django 5.0.3 on 2024-04-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_course_degree_title_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='educations',
        ),
        migrations.AlterModelTable(
            name='experience',
            table='experiences',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skills',
        ),
    ]
